// Stoic Quote desklet — quote data
// Each text/author/source is wrapped in _() so xgettext extracts it
// and translators can localize via po/<lang>.po.

const Gettext = imports.gettext;
const UUID = "stoic-quote@orion";

function _(s) {
    return Gettext.dgettext(UUID, s);
}

var QUOTES = [
    { text: _("The impediment to action advances action. What stands in the way becomes the way."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 5") },
    { text: _("Waste no more time arguing about what a good man should be. Be one."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 10") },
    { text: _("If it is not right, do not do it; if it is not true, do not say it."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 12") },
    { text: _("The best revenge is not to be like your enemy."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 6") },
    { text: _("Loss is nothing else but change, and change is Nature's delight."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 9") },
    { text: _("How much more grievous are the consequences of anger than the causes of it."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 11") },
    { text: _("Never esteem anything as of advantage to you that will make you break your word or lose your self-respect."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 3") },
    { text: _("Do every act of your life as though it were the very last act of your life."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 2") },
    { text: _("You have power over your mind, not outside events. Realize this, and you will find strength."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Very little is needed to make a happy life; it is all within yourself, in your way of thinking."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Accept the things to which fate binds you, and love the people with whom fate brings you together."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 6") },
    { text: _("The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 6") },
    { text: _("It is not death that a man should fear, but he should fear never beginning to live."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 12") },
    { text: _("The happiness of your life depends upon the quality of your thoughts."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("When you wake up in the morning, tell yourself: the people I deal with today will be meddling, ungrateful, arrogant, dishonest, jealous and surly. They are like this because they cannot tell good from evil. But I have seen the beauty of good, and the ugliness of evil, and have recognized that the wrongdoer has a nature related to my own."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 2") },
    { text: _("Look back over the past, with its changing empires that rose and fell, and you can foresee the future too. Its pattern will be the same, deviating only in minor details. And to watch the mortal life of one man is to see them all."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Almost nothing material is needed for a happy life, for he who has understood existence."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Make the best use of what is in your power, and take the rest as it happens."),
      author: _("Epictetus"),
      source: _("Enchiridion, I") },
    { text: _("No man is free who is not master of himself."),
      author: _("Epictetus"),
      source: _("Discourses, 2.1") },
    { text: _("First say to yourself what you would be; and then do what you have to do."),
      author: _("Epictetus"),
      source: _("Discourses, 3.23") },
    { text: _("If you want to improve, be content to be thought foolish and stupid with regard to external things."),
      author: _("Epictetus"),
      source: _("Enchiridion, XIII") },
    { text: _("Freedom is not procured by a full enjoyment of what is desired, but by controlling the desire."),
      author: _("Epictetus"),
      source: _("Discourses, 4.1") },
    { text: _("People are disturbed not by things, but by the views which they take of things."),
      author: _("Epictetus"),
      source: _("Enchiridion, V") },
    { text: _("Seek not the good in external things; seek it in yourself."),
      author: _("Epictetus"),
      source: _("Discourses, 3.24") },
    { text: _("Never say about anything that I have lost it; but only that I have given it back."),
      author: _("Epictetus"),
      source: _("Enchiridion, XI") },
    { text: _("Seek not for the things which happen as you wish; but wish the things which happen to be as they are, and you will have a tranquil life."),
      author: _("Epictetus"),
      source: _("Enchiridion, VIII") },
    { text: _("Wealth consists not in having great possessions, but in having few wants."),
      author: _("Epictetus"),
      source: _("Discourses") },
    { text: _("He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has."),
      author: _("Epictetus"),
      source: _("Discourses") },
    { text: _("Don't explain your philosophy. Embody it."),
      author: _("Epictetus"),
      source: _("Discourses") },
    { text: _("We cannot choose our external circumstances, but we can always choose how we respond to them."),
      author: _("Epictetus"),
      source: _("Enchiridion") },
    { text: _("First learn the meaning of what you say, and then speak."),
      author: _("Epictetus"),
      source: _("Discourses, 1.17") },
    { text: _("You become what you give your attention to. If you yourself don't choose what thoughts and images you expose yourself to, someone else will."),
      author: _("Epictetus"),
      source: _("Discourses") },
    { text: _("There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will."),
      author: _("Epictetus"),
      source: _("Discourses") },
    { text: _("All things are foreign to us; time alone is ours."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, I") },
    { text: _("While we are postponing, life speeds by."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, I") },
    { text: _("It is not the man who has too little, but the man who craves more, that is poor."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, II") },
    { text: _("Begin at once to live, and count each separate day as a separate life."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, CI") },
    { text: _("The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today."),
      author: _("Seneca"),
      source: _("On the Shortness of Life, IX") },
    { text: _("No man was ever wise by chance."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, LXXVI") },
    { text: _("Retire into yourself as much as you can; associate with those who are likely to improve you."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, VII") },
    { text: _("A happy life is one which is in accordance with its own nature."),
      author: _("Seneca"),
      source: _("On the Happy Life, III") },
    { text: _("If you wish to be loved, love."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, IX") },
    { text: _("We suffer more often in imagination than in reality."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, XIII") },
    { text: _("One who is everywhere is nowhere."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, II") },
    { text: _("To live is to fight."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, XCVI") },
    { text: _("Luck is what happens when preparation meets opportunity."),
      author: _("Seneca"),
      source: _("Epistulae Morales") },
    { text: _("True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient."),
      author: _("Seneca"),
      source: _("Letters from a Stoic") },
    { text: _("Better to trip with the feet than with the tongue."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers, 7.26") },
    { text: _("The goal of life is to live in agreement with Nature."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers, 7.87") },
    { text: _("We have two ears and one mouth, so that we should listen more than we say."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers") },
    { text: _("Man conquers the world by conquering himself."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers") },
    { text: _("All the good are friends of one another."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers, 7.32") },
    { text: _("Lead me, Zeus, lead me, Destiny, wherever I have been assigned by you. I will follow without hesitation; and if I am unwilling, because I am wicked, I will follow nonetheless."),
      author: _("Cleanthes"),
      source: _("Hymn to Zeus") },
    { text: _("All things are parts of one single system, which is called Nature; the individual life is good when it is in harmony with Nature."),
      author: _("Cleanthes"),
      source: _("Hymn to Zeus") },
    { text: _("Practice yourself in little things, and thence proceed to greater."),
      author: _("Cleanthes"),
      source: _("Lives of the Eminent Philosophers, 7.168") },
    { text: _("If you accomplish something good with hard work, the labor passes quickly, but the good endures; if you do something shameful in pursuit of pleasure, the pleasure passes quickly, but the shame endures."),
      author: _("Musonius Rufus"),
      source: _("Lectures, VI") },
    { text: _("We must not say that it befits only the philosopher to inquire how one ought to live rightly; for philosophy is nothing else than this — the inquiry into what is fitting and appropriate for a human being."),
      author: _("Musonius Rufus"),
      source: _("Lectures, I") },
    { text: _("Choose to die well while you can; wait too long, and it might become impossible to do so."),
      author: _("Musonius Rufus"),
      source: _("Lectures, VIII") },
    { text: _("The man who is truly good and wise neither struggles with adversity nor complains of his lot; rather, he takes heart from even the harshest of conditions."),
      author: _("Musonius Rufus"),
      source: _("Lectures, X") },
    { text: _("The philosopher's aim is not to hear many lectures and then fall silent, but to live by those already heard."),
      author: _("Musonius Rufus"),
      source: _("Lectures") },
    { text: _("If I had followed the multitude, I would not have studied philosophy."),
      author: _("Chrysippus"),
      source: _("Lives of the Eminent Philosophers, 7.183") },
    { text: _("The virtues are interconnected; whoever truly possesses one virtue possesses them all."),
      author: _("Chrysippus"),
      source: _("Lives of the Eminent Philosophers, 7.125") },
    { text: _("No one is born a sage; goodness is an art which must be learned."),
      author: _("Chrysippus"),
      source: _("Fragments") },
    { text: _("The universe is change; our life is what our thoughts make it."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Dwell on the beauty of life. Watch the stars, and see yourself running with them."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("The art of living is more like wrestling than dancing."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Everything is but what your opinion makes it; and that opinion lies with yourself."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 12") },
    { text: _("Adapt yourself to the things with which your lot has been cast."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 6") },
    { text: _("Confine yourself to the present."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Dig within. There lies the well-spring of good: ever dig, and it will ever flow."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 7") },
    { text: _("Such as are thy habitual thoughts, such also will be the character of thy mind."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 5") },
    { text: _("Difficulties are things that show a person what they are."),
      author: _("Epictetus"),
      source: _("Discourses, 1.24") },
    { text: _("Only the educated are free."),
      author: _("Epictetus"),
      source: _("Discourses, 2.1") },
    { text: _("Know first who you are, and then adorn yourself accordingly."),
      author: _("Epictetus"),
      source: _("Discourses, 3.1") },
    { text: _("If you wish to be a writer, write; if you wish to be a reader, read."),
      author: _("Epictetus"),
      source: _("Discourses, 2.18") },
    { text: _("When you close your doors and make darkness within, remember never to say that you are alone, for you are not alone."),
      author: _("Epictetus"),
      source: _("Discourses, 1.14") },
    { text: _("Lameness is an impediment to the leg, but not to the will."),
      author: _("Epictetus"),
      source: _("Enchiridion, IX") },
    { text: _("It is impossible for a man to learn what he thinks he already knows."),
      author: _("Epictetus"),
      source: _("Discourses, 2.17") },
    { text: _("It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, CIV") },
    { text: _("Difficulties strengthen the mind, as labor does the body."),
      author: _("Seneca"),
      source: _("On Providence, II") },
    { text: _("Sometimes even to live is an act of courage."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, LXXVIII") },
    { text: _("There is no easy way from the earth to the stars."),
      author: _("Seneca"),
      source: _("Hercules Furens") },
    { text: _("He suffers more than necessary, who suffers before it is necessary."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, XCVIII") },
    { text: _("Wherever there is a human being, there is an opportunity for kindness."),
      author: _("Seneca"),
      source: _("On the Happy Life") },
    { text: _("If one does not know to which port one is sailing, no wind is favorable."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, LXXI") },
    { text: _("The day which we fear as our last is but the birthday of eternity."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, CII") },
    { text: _("The most necessary part of philosophy is that which is put into practice."),
      author: _("Musonius Rufus"),
      source: _("Lectures") },
    { text: _("Will not the educated woman be sensible? Yes; will not she be just? Of course."),
      author: _("Musonius Rufus"),
      source: _("Lectures, III") },
    { text: _("The one who is to live well ought to learn beforehand the things that are most necessary."),
      author: _("Musonius Rufus"),
      source: _("Lectures, VI") },
    { text: _("Philosophical doctrine is of no use unless it leads the soul to virtue."),
      author: _("Musonius Rufus"),
      source: _("Lectures, III") },
    { text: _("Fate guides the willing, and drags the unwilling."),
      author: _("Cleanthes"),
      source: _("Seneca, Letters from a Stoic, CVII") },
    { text: _("Happiness is a good flow of life."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers, 7.88") },
    { text: _("The way to attain virtue is to make a habit of self-mastery."),
      author: _("Zeno of Citium"),
      source: _("Lives of the Eminent Philosophers, 7.24") },
    { text: _("No man steps in the same river twice."),
      author: _("Heraclitus"),
      source: _("Fragments, 49a") },
    { text: _("Character is destiny."),
      author: _("Heraclitus"),
      source: _("Fragments, 119") },
    { text: _("Much learning does not teach understanding."),
      author: _("Heraclitus"),
      source: _("Fragments, 40") },
    { text: _("The sun is new each day."),
      author: _("Heraclitus"),
      source: _("Fragments, 6") },
    { text: _("I am a citizen of the world."),
      author: _("Diogenes the Cynic"),
      source: _("Lives of the Eminent Philosophers, 6.63") },
    { text: _("It is the privilege of the gods to want nothing, and of godlike men to want little."),
      author: _("Diogenes the Cynic"),
      source: _("Lives of the Eminent Philosophers, 6.105") },
    { text: _("The most beautiful thing in the world is freedom of speech."),
      author: _("Diogenes the Cynic"),
      source: _("Lives of the Eminent Philosophers, 6.69") },
    { text: _("The mob is the mother of tyrants."),
      author: _("Diogenes the Cynic"),
      source: _("Lives of the Eminent Philosophers, 6.39") },
    { text: _("It is a royal thing to do good and be reviled."),
      author: _("Antisthenes"),
      source: _("Lives of the Eminent Philosophers, 6.3") },
    { text: _("I would rather have men ask why I have no statue than why I have one."),
      author: _("Cato the Younger"),
      source: _("Plutarch, Life of Cato the Younger") },
    { text: _("We are each the center of a series of concentric circles — self, family, neighbors, fellow citizens, humanity. The work is to draw the outer circles toward the center."),
      author: _("Hierocles"),
      source: _("Elements of Ethics") },
    { text: _("Reject your sense of injury, and the injury itself disappears."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Be like the rocky promontory against which the restless surf continually pounds."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Whatever happens to you has been waiting to happen since the beginning of time."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 10") },
    { text: _("Time is a river of passing events; strong is its current."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Do not act as if you had ten thousand years to live."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("How much trouble he avoids who does not look to see what his neighbor says or does."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 4") },
    { text: _("Begin — to begin is half the work; let half still remain. Begin again, and thou wilt have finished."),
      author: _("Marcus Aurelius"),
      source: _("Meditations, Book 12") },
    { text: _("It is the act of an ill-instructed man to blame others; of one whose instruction is beginning, to blame himself; of one whose instruction is complete, to blame neither."),
      author: _("Epictetus"),
      source: _("Enchiridion, V") },
    { text: _("All philosophy lies in two words: sustain and abstain."),
      author: _("Epictetus"),
      source: _("Fragment, via Aulus Gellius") },
    { text: _("Don't let the force of an impression when it first hits you knock you off your feet."),
      author: _("Epictetus"),
      source: _("Discourses, 2.18") },
    { text: _("There is nothing good or evil save in the will."),
      author: _("Epictetus"),
      source: _("Discourses, 3.10") },
    { text: _("Every night ask yourself: what weakness did I overcome today? What virtue did I acquire?"),
      author: _("Seneca"),
      source: _("On Anger, III") },
    { text: _("As long as you live, keep learning how to live."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, LXXVI") },
    { text: _("It is a rough road that leads to the heights of greatness."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, LXXXIV") },
    { text: _("Anger, if not restrained, is more hurtful to us than the injury that provokes it."),
      author: _("Seneca"),
      source: _("On Anger") },
    { text: _("Let us prepare our minds as if we had come to the very end of life."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, CI") },
    { text: _("Throw aside all hindrances and devote your time to the cultivation of a sound mind."),
      author: _("Seneca"),
      source: _("Letters from a Stoic, XVI") },
    { text: _("All disturbances arise from false judgments."),
      author: _("Chrysippus"),
      source: _("Plutarch, On Stoic Self-Contradictions") },
];
