// Promesas Bíblicas — datos de promesas

const Gettext = imports.gettext;
const UUID = "promesas-biblicas@largacha";

function _(s) {
    return Gettext.dgettext(UUID, s);
}

var PROMESAS = [
    { text: _("No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré, siempre te sustentaré con la diestra de mi justicia."),
      author: _("Isaías 41:10"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová es mi pastor; nada me faltará."),
      author: _("Salmos 23:1"),
      source: _("Antiguo Testamento") },
    { text: _("Encomienda a Jehová tus obras, y tus pensamientos serán afirmados."),
      author: _("Proverbios 16:3"),
      source: _("Antiguo Testamento") },
    { text: _("Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis."),
      author: _("Jeremías 29:11"),
      source: _("Antiguo Testamento") },
    { text: _("Esfuérzate y sé valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo dondequiera que vayas."),
      author: _("Josué 1:9"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová es mi luz y mi salvación; ¿de quién temeré? Jehová es la fortaleza de mi vida; ¿de quién he de atemorizarme?"),
      author: _("Salmos 27:1"),
      source: _("Antiguo Testamento") },
    { text: _("Confía en Jehová con todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas."),
      author: _("Proverbios 3:5-6"),
      source: _("Antiguo Testamento") },
    { text: _("Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones."),
      author: _("Salmos 46:1"),
      source: _("Antiguo Testamento") },
    { text: _("Porque como un padre se compadece de sus hijos, así ha tenido Jehová compasión de nosotros."),
      author: _("Salmos 103:13"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová está cerca de los que tienen quebrantado el corazón, y salva a los contritos de espíritu."),
      author: _("Salmos 34:18"),
      source: _("Antiguo Testamento") },
    { text: _("Mas los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán."),
      author: _("Isaías 40:31"),
      source: _("Antiguo Testamento") },
    { text: _("No temas, porque no serás avergonzado; ni te sonrojes, porque no serás afrentado; sino que te olvidarás de la vergüenza de tu juventud."),
      author: _("Isaías 54:4"),
      source: _("Antiguo Testamento") },
    { text: _("Cuando pases por las aguas, yo estaré contigo; y si por los ríos, no te anegarán. Cuando pases por el fuego, no te quemarás, ni la llama arderá en ti."),
      author: _("Isaías 43:2"),
      source: _("Antiguo Testamento") },
    { text: _("Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios."),
      author: _("Salmos 103:2"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová te bendecirá y te guardará; Jehová hará resplandecer su rostro sobre ti, y tendrá de ti misericordia."),
      author: _("Números 6:24-25"),
      source: _("Antiguo Testamento") },
    { text: _("El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente."),
      author: _("Salmos 91:1"),
      source: _("Antiguo Testamento") },
    { text: _("Porque él libra al pobre cuando clama, y al afligido que no tiene quien le ayude."),
      author: _("Salmos 72:12"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová guarda a todos los que le aman, mas destruirá a todos los impíos."),
      author: _("Salmos 145:20"),
      source: _("Antiguo Testamento") },
    { text: _("He aquí, yo estoy contigo, y te guardaré por dondequiera que fueres, y volveré a traerte a esta tierra; porque no te dejaré hasta que haya hecho lo que te he dicho."),
      author: _("Génesis 28:15"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová peleará por vosotros, y vosotros estaréis tranquilos."),
      author: _("Éxodo 14:14"),
      source: _("Antiguo Testamento") },
    { text: _("Porque él sacia al alma menesterosa, y llena de bien al alma hambrienta."),
      author: _("Salmos 107:9"),
      source: _("Antiguo Testamento") },
    { text: _("Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas."),
      author: _("Josué 1:9"),
      source: _("Antiguo Testamento") },
    { text: _("Los que sembraron con lágrimas, con regocijo segarán. Irán andando y llorando los que llevan la semilla; pero volverán cantando, trayendo sus gavillas."),
      author: _("Salmos 126:5-6"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová dará fuerza a su pueblo; Jehová bendecirá a su pueblo con paz."),
      author: _("Salmos 29:11"),
      source: _("Antiguo Testamento") },
    { text: _("En el día que temo, yo en ti confío."),
      author: _("Salmos 56:3"),
      source: _("Antiguo Testamento") },
    { text: _("El ángel de Jehová acampa alrededor de los que le temen, y los defiende."),
      author: _("Salmos 34:7"),
      source: _("Antiguo Testamento") },
    { text: _("Gustad, y ved que es bueno Jehová; dichoso el hombre que confía en él."),
      author: _("Salmos 34:8"),
      source: _("Antiguo Testamento") },
    { text: _("Porque yo derramaré aguas sobre el sequedal, y ríos sobre la tierra árida; mi Espíritu derramaré sobre tu generación, y mi bendición sobre tus renuevos."),
      author: _("Isaías 44:3"),
      source: _("Antiguo Testamento") },
    { text: _("Porque los montes se moverán, y los collados temblarán, pero no se apartará de ti mi misericordia, ni el pacto de mi paz se quebrantará, dijo Jehová, el que tiene misericordia de ti."),
      author: _("Isaías 54:10"),
      source: _("Antiguo Testamento") },
    { text: _("He aquí, yo soy Jehová, el Dios de toda carne; ¿habrá algo que sea difícil para mí?"),
      author: _("Jeremías 32:27"),
      source: _("Antiguo Testamento") },
    { text: _("No desecho la gracia de Dios; pues si por la ley fuese la justicia, entonces por demás murió Cristo."),
      author: _("Gálatas 2:21"),
      source: _("Nuevo Testamento") },
    { text: _("Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar."),
      author: _("Mateo 11:28"),
      source: _("Nuevo Testamento") },
    { text: _("Y yo estoy con vosotros todos los días, hasta el fin del mundo."),
      author: _("Mateo 28:20"),
      source: _("Nuevo Testamento") },
    { text: _("No os afanéis por vuestra vida, qué habéis de comer o qué habéis de beber; ni por vuestro cuerpo, qué habéis de vestir."),
      author: _("Mateo 6:25"),
      source: _("Nuevo Testamento") },
    { text: _("Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas."),
      author: _("Mateo 6:33"),
      source: _("Nuevo Testamento") },
    { text: _("Pedid, y se os dará; buscad, y hallaréis; llamad, y se os abrirá."),
      author: _("Mateo 7:7"),
      source: _("Nuevo Testamento") },
    { text: _("Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna."),
      author: _("Juan 3:16"),
      source: _("Nuevo Testamento") },
    { text: _("La paz os dejo, mi paz os doy; yo no os la doy como el mundo la da. No se turbe vuestro corazón, ni tenga miedo."),
      author: _("Juan 14:27"),
      source: _("Nuevo Testamento") },
    { text: _("Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí."),
      author: _("Juan 14:6"),
      source: _("Nuevo Testamento") },
    { text: _("Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados, y limpiarnos de toda maldad."),
      author: _("1 Juan 1:9"),
      source: _("Nuevo Testamento") },
    { text: _("Mayor es el que está en vosotros, que el que está en el mundo."),
      author: _("1 Juan 4:4"),
      source: _("Nuevo Testamento") },
    { text: _("Echando toda vuestra ansiedad sobre él, porque él tiene cuidado de vosotros."),
      author: _("1 Pedro 5:7"),
      source: _("Nuevo Testamento") },
    { text: _("Mas Dios muestra su amor para con nosotros, en que siendo aún pecadores, Cristo murió por nosotros."),
      author: _("Romanos 5:8"),
      source: _("Nuevo Testamento") },
    { text: _("Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados."),
      author: _("Romanos 8:28"),
      source: _("Nuevo Testamento") },
    { text: _("Por lo cual estoy seguro de que ni la muerte, ni la vida, ni ángeles, ni principados, ni potestades, ni lo presente, ni lo por venir, ni lo alto, ni lo profundo, ni ninguna otra cosa creada nos podrá separar del amor de Dios, que es en Cristo Jesús Señor nuestro."),
      author: _("Romanos 8:38-39"),
      source: _("Nuevo Testamento") },
    { text: _("No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento, para que comprobéis cuál sea la buena voluntad de Dios, agradable y perfecta."),
      author: _("Romanos 12:2"),
      source: _("Nuevo Testamento") },
    { text: _("Todo lo puedo en Cristo que me fortalece."),
      author: _("Filipenses 4:13"),
      source: _("Nuevo Testamento") },
    { text: _("Mi Dios, pues, suplirá todo lo que os falta conforme a sus riquezas en gloria en Cristo Jesús."),
      author: _("Filipenses 4:19"),
      source: _("Nuevo Testamento") },
    { text: _("Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración y ruego, con acción de gracias. Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones y vuestros pensamientos en Cristo Jesús."),
      author: _("Filipenses 4:6-7"),
      source: _("Nuevo Testamento") },
    { text: _("Porque somos hechura suya, creados en Cristo Jesús para buenas obras, las cuales Dios preparó de antemano para que anduviésemos en ellas."),
      author: _("Efesios 2:10"),
      source: _("Nuevo Testamento") },
    { text: _("Pero Dios, que es rico en misericordia, por su gran amor con que nos amó, aun estando nosotros muertos en pecados, nos dio vida juntamente con Cristo."),
      author: _("Efesios 2:4-5"),
      source: _("Nuevo Testamento") },
    { text: _("Jehová es mi fortaleza y mi escudo; en él confió mi corazón, y fui ayudado."),
      author: _("Salmos 28:7"),
      source: _("Antiguo Testamento") },
    { text: _("Porque no nos ha dado Dios espíritu de cobardía, sino de poder, de amor y de dominio propio."),
      author: _("2 Timoteo 1:7"),
      source: _("Nuevo Testamento") },
    { text: _("Fiel es el que os llama, el cual también lo hará."),
      author: _("1 Tesalonicenses 5:24"),
      source: _("Nuevo Testamento") },
    { text: _("Por tanto, no desmayamos; antes aunque este nuestro hombre exterior se va desgastando, el interior no obstante se renueva de día en día."),
      author: _("2 Corintios 4:16"),
      source: _("Nuevo Testamento") },
    { text: _("Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios."),
      author: _("Efesios 2:8"),
      source: _("Nuevo Testamento") },
    { text: _("Estando persuadido de esto, que el que comenzó en vosotros la buena obra, la perfeccionará hasta el día de Jesucristo."),
      author: _("Filipenses 1:6"),
      source: _("Nuevo Testamento") },
    { text: _("Así que, hermanos míos amados, estad firmes y constantes, creciendo en la obra del Señor siempre, sabiendo que vuestro trabajo en el Señor no es en vano."),
      author: _("1 Corintios 15:58"),
      source: _("Nuevo Testamento") },
    { text: _("No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir, sino que dará también juntamente con la tentación la salida, para que podáis soportar."),
      author: _("1 Corintios 10:13"),
      source: _("Nuevo Testamento") },
    { text: _("Consolaos, consolaos, pueblo mío, dice vuestro Dios."),
      author: _("Isaías 40:1"),
      source: _("Antiguo Testamento") },
    { text: _("Jehová, en la tribulación te buscaron; derramaron oración cuando los castigaste."),
      author: _("Isaías 26:16"),
      source: _("Antiguo Testamento") },
    { text: _("El que no escatimó ni a su propio Hijo, sino que lo entregó por todos nosotros, ¿cómo no nos dará también con él todas las cosas?"),
      author: _("Romanos 8:32"),
      source: _("Nuevo Testamento") },
    { text: _("Venid luego, dice Jehová, y estemos a cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos; si fueren rojos como el carmesí, vendrán a ser como blanca lana."),
      author: _("Isaías 1:18"),
      source: _("Antiguo Testamento") },
    { text: _("Porque yo Jehová no cambio; por esto, hijos de Jacob, no habéis sido consumidos."),
      author: _("Malaquías 3:6"),
      source: _("Antiguo Testamento") },
    { text: _("Sé fuerte y valiente, no temas ni te intimides delante de ellos, porque Jehová tu Dios es el que va contigo; no te dejará ni te desamparará."),
      author: _("Deuteronomio 31:6"),
      source: _("Antiguo Testamento") },
    { text: _("Mas el que me oye, habitará confiadamente y vivirá tranquilo, sin temor del mal."),
      author: _("Proverbios 1:33"),
      source: _("Antiguo Testamento") },
    { text: _("Porque Jehová tu Dios está en medio de ti, poderoso es; él salvará; se gozará sobre ti con alegría, callará de amor, se regocijará sobre ti con cánticos."),
      author: _("Sofonías 3:17"),
      source: _("Antiguo Testamento") },
    { text: _("Esforzaos todos vosotros los que esperáis en Jehová, y tome aliento vuestro corazón."),
      author: _("Salmos 31:24"),
      source: _("Antiguo Testamento") },
];
